name: order-api-pipeline
permissions:
  contents: read
  id-token: write
  actions: write
  packages: write
on:
  workflow_dispatch:

jobs:
  build:
   runs-on: ubuntu-latest
   steps:
     - name: "checku_out"
       uses: actions/checkout@v6.0.2
     - name: "github_registry_login"
       uses: docker/login-action@v4
       with:
         registry: ghcr.io
         username: ${{ github.actor }}
         password: ${{ secrets.GITHUB_TOKEN }}
     - name: "present working directory"
       run: |
           pwd
           ls -lah
    
     - name: "OrdersMicroservice-api-image-build"
       working-directory: OrdersMicroservice
       run: |
          docker --version
          docker build -f Dockerfile -t ghcr.io/ptm9966/kfc-ordersmicroservice:${{ github.sha }} .
          docker images
     - name: "ProductMicroservice-api-image-build"
       working-directory: ProductMicroservice
       run: |
          docker --version
          docker build -f Dockerfile -t ghcr.io/ptm9966/kfc-productmicroservice:${{ github.sha }} .
          docker images
     - name: "UserMicroservice-api-image-build"
       working-directory: UserMicroservice
       run: |
          docker --version
          docker build -f Dockerfile -t ghcr.io/ptm9966/kfc-usermicroservice:${{ github.sha }} .
          docker images
     - name: "cartMicroservice-api-image-build"
       working-directory: cartMicroservice
       run: |
          docker --version
          docker build -f Dockerfile -t ghcr.io/ptm9966/kfc-cartmicroservice:${{ github.sha }} .
          docker images

     - name: "Frontend-image-build"
       working-directory: Frontend
       shell: bash
       run: |
          docker build \
          --build-arg REACT_APP_CART_SERVICE_URL="" \
          --build-arg REACT_APP_ORDERS_URL=https:"" \
          --build-arg REACT_APP_USERS_URL=https://<users-app-url> \
          --build-arg REACT_APP_PRODUCTS_URL=https://<products-app-url> \
          -f Dockerfile -t ghcr.io/ptm9966/kfc-frontendmicorservice:${{ github.sha }} .

     - name: "Push image to github"
       run: |
          docker push ghcr.io/ptm9966/kfc-frontendmicorservice:${{ github.sha }}
          docker push ghcr.io/ptm9966/kfc-cartmicroservice:${{ github.sha }}
          docker push ghcr.io/ptm9966/kfc-usermicroservice:${{ github.sha }}
          docker push ghcr.io/ptm9966/kfc-productmicroservice:${{ github.sha }}
          docker push ghcr.io/ptm9966/kfc-ordersmicroservice:${{ github.sha }}
    




          
          
       
       
  
